node {
  cookie = "emqx50elixir"
  data_dir = "data"
}

mqtt {
  max_packet_size = "2000000B"
}

# EMQX requires a really high max_heap_size value in order to
# not run out of memory if debug logs are enabled (~1000MB).
# For this reason, just disable shutdown completely.
force_shutdown {
  enable = false
}

authentication = [
  {
    mechanism = "password_based"
    backend = "built_in_database"
  }
  {
    mechanism = "scram"
    backend = "built_in_database"
    algorithm = "sha256"
    iteration_count = 4096
  }
]
