on: [pull_request, workflow_dispatch, workflow_call]
name: Integration Tests

jobs:
  integration_tests_mosquitto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install toolchain
        run: rustup show

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Prepare Mosquitto Configuration
        run: |
          cp .ci/mqtt_pass_plain.txt .ci/mqtt_pass_hashed.txt
          sudo chown root:root .ci/mqtt_pass_hashed.txt
          sudo chmod 600 .ci/mqtt_pass_hashed.txt

          docker run --rm \
            -v $PWD/.ci:/.ci \
            eclipse-mosquitto:2.1.2-alpine \
            mosquitto_passwd -U .ci/mqtt_pass_hashed.txt

          sudo chown 1883:1883 .ci/mqtt_pass_hashed.txt

      - name: Start Mosquitto
        run: |
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v $PWD/.ci:/.ci \
            -v $PWD/.ci/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2.1.2-alpine
          timeout 10s sh -c 'until docker logs mosquitto 2>&1 | grep "mosquitto version 2.1.2 running"; do sleep 0.1; done'

      - name: Run integration tests
        run: RUST_LOG=trace cargo test integration --features "log" -- --show-output

      - name: Restart Mosquitto
        run: |
          docker rm -f mosquitto
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v $PWD/.ci:/.ci \
            -v $PWD/.ci/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2.1.2-alpine
          timeout 10s sh -c 'until docker logs mosquitto 2>&1 | grep "mosquitto version 2.1.2 running"; do sleep 0.1; done'

      - name: Run mosquitto-only integration tests
        run: RUST_LOG=trace cargo test mosquitto_only --features "log" -- --show-output --ignored

  integration_tests_hive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install toolchain
        run: rustup show

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Prepare HiveMQ Configuration
        run: |
          curl -LO https://github.com/hivemq/hivemq-file-rbac-extension/releases/download/4.6.8/hivemq-file-rbac-extension-4.6.8.zip
          unzip hivemq-file-rbac-extension-4.6.8.zip
          cp .ci/hive_cred.xml hivemq-file-rbac-extension/conf/credentials.xml
          cp .ci/hive_extension_config.xml hivemq-file-rbac-extension/conf/config.xml

      - name: Start HiveMQ
        run: |
          docker run -d \
            --name hivemq \
            -p 1883:1883 \
            -v $PWD/.ci/hive_config.xml:/opt/hivemq/conf/config.xml \
            -v $PWD/hivemq-file-rbac-extension:/opt/hivemq/extensions/hivemq-file-rbac-extension \
            hivemq/hivemq-ce:2026.5
          timeout 30s sh -c 'until docker logs hivemq 2>&1 | grep "Started HiveMQ in"; do sleep 0.1; done'

      - name: Run integration tests
        run: RUST_LOG=trace cargo test integration --features "log" -- --show-output

      - name: Restart HiveMQ
        run: |
          docker rm -f hivemq
          docker run -d \
            --name hivemq \
            -p 1883:1883 \
            -v $PWD/.ci/hive_config.xml:/opt/hivemq/conf/config.xml \
            -v $PWD/hivemq-file-rbac-extension:/opt/hivemq/extensions/hivemq-file-rbac-extension \
            hivemq/hivemq-ce:2026.5
          timeout 30s sh -c 'until docker logs hivemq 2>&1 | grep "Started HiveMQ in"; do sleep 0.1; done'

      - name: Run hive-only integration tests
        run: RUST_LOG=trace cargo test hive_only --features "log" -- --show-output --ignored

  integration_tests_emqx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install toolchain
        run: rustup show

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Start EMQX
        run: |
          docker run -d \
            --name emqx \
            -p 1883:1883 \
            -v $PWD/.ci/emqx.conf:/opt/emqx/etc/emqx.conf \
            -v $PWD/.ci/emqx_users.csv:/opt/emqx/etc/auth-built-in-db-bootstrap.csv \
            emqx/emqx:6.2.2
          timeout 30s sh -c 'until docker logs emqx 2>&1 | grep "EMQX Enterprise 6.2.2 is running now!"; do sleep 0.1; done'

      - name: Run integration tests
        run: RUST_LOG=trace cargo test integration --features "log" -- --show-output

      - name: Restart EMQX
        run: |
          docker rm -f emqx
          docker run -d \
            --name emqx \
            -p 1883:1883 \
            -v $PWD/.ci/emqx.conf:/opt/emqx/etc/emqx.conf \
            -v $PWD/.ci/emqx_users.csv:/opt/emqx/etc/auth-built-in-db-bootstrap.csv \
            emqx/emqx:6.2.2
          timeout 30s sh -c 'until docker logs emqx 2>&1 | grep "EMQX Enterprise 6.2.2 is running now!"; do sleep 0.1; done'

      - name: Run emqx-only integration tests
        run: RUST_LOG=trace cargo test emqx_only --features "log" -- --show-output --ignored
