on: [pull_request, workflow_dispatch, workflow_call]
name: Integration Tests

jobs:
  integration_tests_mosquitto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install toolchain
        run: rustup show

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Prepare Mosquitto Configuration
        run: |
          cp .ci/mqtt_pass_plain.txt .ci/mqtt_pass_hashed.txt
          sudo chown root:root .ci/mqtt_pass_hashed.txt
          sudo chmod 600 .ci/mqtt_pass_hashed.txt

          docker run --rm \
            -v $PWD/.ci:/.ci \
            eclipse-mosquitto:2.1.2-alpine \
            mosquitto_passwd -U .ci/mqtt_pass_hashed.txt

          sudo chown 1883:1883 .ci/mqtt_pass_hashed.txt

      - name: Start Mosquitto
        run: |
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v $PWD/.ci:/.ci \
            -v $PWD/.ci/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2.1.2-alpine
          timeout 10s sh -c 'until docker logs mosquitto 2>&1 | grep "mosquitto version 2.1.2 running"; do sleep 0.1; done'

      - name: Run integration tests
        run: RUST_LOG=trace cargo test integration --features "log" -- --show-output

      - name: Restart Mosquitto
        run: |
          docker rm -f mosquitto
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v $PWD/.ci:/.ci \
            -v $PWD/.ci/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2.1.2-alpine
          timeout 10s sh -c 'until docker logs mosquitto 2>&1 | grep "mosquitto version 2.1.2 running"; do sleep 0.1; done'

      - name: Run mosquitto-only integration tests
        run: RUST_LOG=trace cargo test mosquitto_only --features "log" -- --show-output --ignored

  integration_tests_hive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install toolchain
        run: rustup show

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Start HiveMQ
        run: |
          curl -LO https://github.com/hivemq/hivemq-community-edition/releases/download/2025.5/hivemq-ce-2025.5.zip
          unzip hivemq-ce-2025.5.zip
          curl -LO https://github.com/hivemq/hivemq-file-rbac-extension/releases/download/4.6.8/hivemq-file-rbac-extension-4.6.8.zip
          unzip hivemq-file-rbac-extension-4.6.8.zip
          mv hivemq-file-rbac-extension hivemq-ce-2025.5/extensions
          cp .ci/hive_config.xml hivemq-ce-2025.5/conf/config.xml
          cp .ci/hive_cred.xml hivemq-ce-2025.5/extensions/hivemq-file-rbac-extension/credentials.xml
          cp .ci/hive_extension_config.xml hivemq-ce-2025.5/extensions/hivemq-file-rbac-extension/conf/config.xml
          hivemq-ce-2025.5/bin/run.sh &
          sleep 3

      - name: Run integration tests
        run: RUST_LOG=trace cargo test integration --features "log" -- --show-output

      - name: Restart HiveMQ
        run: |
          pkill -f hivemq-ce || true
          sleep 5
          hivemq-ce-2025.5/bin/run.sh &
          sleep 3

      - name: Run hive-only integration tests
        run: RUST_LOG=trace cargo test hive_only --features "log" -- --show-output --ignored
